ALTER TABLE STUDENT1 ADD SEM INT;
ALTER TABLE STUDENT1 MODIFY SEM VARCHAR(10);
ALTER TABLE DEPARTMENT RENAME COLUMN DEP_NAME TO DEPTNAME;
ALTER TABLE STUDENT1 DROP COLUMN SEMESTER;

ALTER TABLE PRODUCT RENAME COLUMN CATEGORY TO CTG;

ALTER TABLE PROUDUCTS  CATEGORYID=1 WHERE PRODUCTID=2;       