SELECT P.PRODUCTID,
       P.PRODUCTNAME,
       C.CATEGORYNAME,
       P.PRICE
FROM PRODUCT P
INNER JOIN CATEGORIES C
ON P.CATEGORYID = C.CATEGORYID
ORDER BY P.PRICE;

SELECT P.PRODUCTID,
       P.PRODUCTNAME,
       C.CATEGORYNAME,
       P.PRICE
FROM PRODUCTS P INNER JOIN CATEGORIES C
ON P.CATEGORYID = C.CATEGORYID
ORDER BY P.PRICE;



SELECT P.PRODUCTID,
       P.PRODUCTNAME,
       C.CATEGORYNAME,
       P.PRICE
FROM PRODUCTS P
LEFT OUTER JOIN CATEGORIES C
ON P.CATEGORYID = C.CATEGORYID
WHERE P.PRODUCTNAME = 'LAPTOP';



SELECT P.PRODUCTID,
       P.PRODUCTNAME,
       C.CATEGORYNAME,
       P.PRICE
FROM PRODUCTS P
RIGHT OUTER JOIN CATEGORIES C
ON P.CATEGORYID = C.CATEGORYID
WHERE C.CATEGORYNAME = 'CLOTHING';



SELECT P.PRODUCTID,
       P.PRODUCTNAME,
       C.CATEGORYNAME,
       P.PRICE
FROM PRODUCTS P
FULL OUTER JOIN CATEGORIES C
ON P.CATEGORYID = C.CATEGORYID
WHERE P.PRICE = (SELECT MIN(PRICE) FROM PRODUCTS);



SELECT PRODUCTID,
       PRODUCTNAME,
       CATEGORYNAME,
       PRICE
FROM PRODUCTS
NATURAL JOIN CATEGORIES
WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS);
