#nearly_equal - if string a can be generated by a single mutation on b.

def nearly_equal(a, b):
    if len(a) != len(b):
        print("Not Nearly equal")
        return False

    diff_count = 0
    for i in range(len(a)):
        if a[i] != b[i]:
            diff_count += 1

    if diff_count > 1:
        print("Not Nearly Equal")
        return False
    elif diff_count == 1:
        print("Nearly equal")
        return True
    else:
        print("Identical strings, not nearly equal")
        return False

str1 = input("Enter the first string: ")
str2 = input("Enter the second string:")
result = nearly_equal(str1, str2)
